### ISSUE TITLE
Annotation of copy-number-regulated genes

### ISSUE THREAD

**Issue by raylim** [jrflab/modules#10]

**Comment by inodb** [comment]
Actually that commit added gene annotations but not the copy number regulated genes annotations

**Comment by inodb** [comment]
That still needs to be done. Problem was that it can add a lot of columns, since the annotation is per subtype so we need some way of choosing what annotations to add. Maybe as a parameter to the Makefile

**Comment by raylim** [comment]
how sparse is the matrix per subtype? Maybe we could collapse it into a single annotation column

**Comment by raylim** [comment]
i.e., a single column that lists the number of subtypes where a gene is copy-number regulated

**Comment by inodb** [comment]
I guess that could work as well
