### ISSUE TITLE
run sufam to get base genomic information for all mutations before pyclone

### ISSUE THREAD

**Issue by hxrts** [jrflab/modules#105]

**Comment by inodb** [comment]
I guess you could copy these lines: 

https://github.com/jrflab/modules/blob/master/recurrent_mutations/report.mk#L21-L35

only thing is that this calls only NS mutations, so you'd have to change the input files to use all mutations.

Another option that would take less computational time in the future but more coding time now would be to make some sufam module that calls all mutations in all samples. Perhaps generating some subselections by default. The other modules would then use the output from that one by selecting the right subselection.

**Comment by hxrts** [comment]
hmm. let's go over this in more detail at our meeting today.
