### ISSUE TITLE
Improve facets results for high coverage samples

### ISSUE THREAD

**Issue by inodb** [jrflab/modules#155]
I ran facets with `FACETS_UNION_GATK_DBSNP=true` on a couple of cases with very high coverage, but the results aren't much better compared to just using dbsnp. Maybe we should try subsampling or something else.

CC
@hxrts

**Comment by inodb** [comment]
As @raylim mentioned, this is prolly mostly an improvement for lower coverage samples, so perhaps we should try on a low coverage or small target region case. This however still leaves the problem of facets misbehaving on a high coverage samples

**Comment by hxrts** [comment]
@inodb @raylim the inclusion of GATK calls will only address low or sparse coverage. Facets has a hard cutoff for normal depth ([issue thread](https://github.com/mskcc/facets/issues/5)). I performed the downsampling they suggested but opted not to reply as the results were confounded by other issues i.e. data set comprised several super high-depth normals, an extremely sparse target set (intersection of our 3 breast panels) + a number of very low depth tumor samples, nightmare scenario really.
