### ISSUE TITLE
ABSOLUTE variant input differs from MUTATION_SUMMARY sheet

### ISSUE THREAD

**Issue by hxrts** [jrflab/modules#179]
ABSOLUTE uses the following file sets:

```
tables/%.strelka_varscan_indels.tab.txt
tables/%.$(call SOMATIC_VCF_SUFFIXES,mutect).tab.txt
```

whereas the MUTATION_SUMMARY uses a curated collection of the following set:

```
alltables/allTN...
```

**Comment by inodb** [comment]
Just making sure I understand correctly. MUTATION_SUMMARY is not a subset of the mutations for ABSOLUTE?

**Comment by hxrts** [comment]
Yes, that's correct. I have a local script that pulls directly from the excel sheet. Will port it over shortly and do a pull request.
