### ISSUE TITLE
Excel output raw file sheet unparseable with pandas

### ISSUE THREAD

**Issue by inodb** [jrflab/modules#41]
The raw file sheets are created from a groupby object. When that object is
ouputted to an excel sheet, cells with the same value are merged. It looks nice
visually in the sheet but it makes the sheet unparseable, so for the raw data
sheets it is probably better to turn the groupby object to a regular dataframe
before outputting to excel.

**Comment by hxrts** [comment]
relevant [issue](https://github.com/jrflab/modules/issues/83), replace tsv as main parsing file.

**Comment by inodb** [comment]
tsvs from excel now in `summary/tsv/`
