### ISSUE TITLE
Install all dependencies to make the pipeline more portable

### ISSUE THREAD

**Issue by inodb** [jrflab/modules#76]
We should come up with a way to install all dependencies easily so we can make the pipeline more portable. Couple of ideas:
- Create a VM with all dependencies
  - Maybe for just the parts that require little computational power
- Use conda similar to bcbio
  - http://lh3.github.io/2015/12/07/bioconda-the-best-package-manager-so-far/
  - https://bioconda.github.io/
  - https://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html

**Comment by hxrts** [comment]
@raylim what are our VM options on the cluster? can we use virtualbox?
