### ISSUE TITLE
mutation summary absolute additions break

### ISSUE THREAD

**Issue by hxrts** [jrflab/modules#84]
DId a quick fix removing absolute portion of the make file so the master branch is functional. @inodb you'll probably want to revert this once the bug is fixed.

Temp patch commit [here](https://github.com/jrflab/modules/commit/b50b5f68d8a430a1422b08d02326a79225117552).

**Comment by hxrts** [comment]
@inodb I believe you've fixed this already & can close.

**Comment by inodb** [comment]
Yup
