### ISSUE TITLE
Add configure script & master config file

### ISSUE THREAD

**Issue by inodb** [jrflab/modules#87]
Currently the way the config file is read is rather complicated using a lot of bash tools. Not very portable. If possible it would be nice to get a language agnostic config file as well, such as json or yaml instead of just a make config file

**Comment by raylim** [comment]
We could do away with samples.txt and sample_sets.txt in the process I imagine

**Comment by hxrts** [comment]
Combining everything into a single config would be quite nice – making it easier to track project run params. I'm in favor of YAML for readability.

**Comment by hxrts** [comment]
ray should add example file here
