### ISSUE TITLE
agree on consistant mutation_summary.xlsx / .tsv column headers

### ISSUE THREAD

**Issue by hxrts** [jrflab/modules#89]
not complete but some changes are listed below:

| current | CHROM | POS | TUMOR_SAMPLE | NORMAL_SAMPLE | ANN[*].GENE | ANN[*].HGVS_P | ANN[*].HGVS_C | ANN[*].EFFECT | TUMOR_MAF | NORMAL_MAF | TUMOR.DP | NORMAL.DP | dbNSFP_ExAC_Adj_AF | dbNSFP_MutationTaster_pred | cancer_gene_census | kandoth | lawrence | hap_insuf | REF | ALT | ANN[*].IMPACT |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| proposed | CHROM | POS | TUMOR_SAMPLE | NORMAL_SAMPLE | GENE | AA_CHANGE | BASE_CHANGE | EVENT_EFFECT | TUMOR_MAF | NORMAL_MAF | TUMOR_DP | NORMAL_DP | dbNSFP_ExAC_Adj_AF ?? | MUT_TASTER_PRED | CG_CENSUS | KANDOTH | LAWRENCE | HAP_INSUFFICIENT | REF_BASE | ALT_BASE | EVENT_IMPACT |

**Comment by charlottekyng** [comment]
please make sure ExAC comes from the actual ExAC annotation not from dbNSFP.

To avoid unconventional/ambiguous terminology, please consider these instead.
BASE_CHANGE -> cDNA_CHANGE
EVENT_EFFECT -> EFFECT
CG_CENSUS -> CANCER_GENE_CENSUS
HAP_INSUFFICIENT ->HAPLOINSUFFICIENCY
