### ISSUE TITLE
facets post-processing step

### ISSUE THREAD

**Issue by hxrts** [jrflab/modules#92]
script for cleaning incomplete facets copy number calls of categorical cases, eg:
- chromosome ends
- deletions > X basepairs in length (reports repairs)

**Comment by hxrts** [comment]
I wrote a functional standalone script [here](https://github.com/jrflab/pascal/blob/master/copy_number/post_facets.R) that fills chromosome tails and inner-chromosome gaps with their nearest neighbors by genomic position. Will integrate this into modules shortly.

**Comment by inodb** [comment]
:+1:

**Comment by raylim** [comment]
neat

**Comment by inodb** [comment]
One thing to note though. For calling loh we want to use the `cncf.txt` files since you get the amp/dels at segment level instead of at gene level. It therefore might be good to clean the upstream `cncf.txt` file instead of the derived `geneCN.txt` file if possible

**Comment by hxrts** [comment]
@inodb I hear you, I think this deserves further discussion since the gaps largely indicate lack of information to make the CN call. I'm not sure if it's better to fill in absent segments or to say there isn't sufficient information to determine LOH in those regions. If we decide to clean the .cncf files, this code could be ported with a few modifications.
